spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimeZoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysqljamilA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        ejb:
          interceptor: com.lakhalifi.GestionDeStock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8081

flickr:
  apiKey: 8aa79255f581f81a8ab84c62ef8ad40b
  apiSecret: cc2a1e373d456fc6
  appKey: 72157720895569347-addff0a1e1165ead
  appSecret: 8085af08b96629bb

